window.nacencommData = {
  company: {
    name: "NACENCOMM",
    badge: "CA2",
    hotline: "1900 5454 07",
    subtitle: "Tổng Công ty Truyền thông",
  },
  paymentMethods: [
    { value: "bank", title: "Chuyển khoản ngân hàng", note: "Xác nhận nhanh cho hồ sơ doanh nghiệp." },
    { value: "qr", title: "QR Code (VietQR)", note: "Phù hợp khi khách hàng muốn thao tác ngay trên điện thoại." },
    { value: "wallet", title: "Ví điện tử", note: "Mock MoMo / ZaloPay cho phần demo." },
    { value: "postpaid", title: "Thanh toán sau", note: "Áp dụng khi chốt qua hợp đồng hoặc tư vấn." },
  ],
  remoteSigning: {
    targetOptions: [
      {
        value: "organization",
        icon: "🏢",
        title: "Tổ chức / Doanh nghiệp",
        subtitle: "Hiển thị đầy đủ phần thông tin doanh nghiệp ở bước tiếp theo.",
        requiresOrg: true,
      },
      {
        value: "employee",
        icon: "👨‍💼",
        title: "Cá nhân thuộc tổ chức / Doanh nghiệp",
        subtitle: "Khai báo doanh nghiệp và cá nhân sử dụng chứng thư số.",
        requiresOrg: true,
      },
      {
        value: "individual",
        icon: "👤",
        title: "Cá nhân",
        subtitle: "Chỉ hiển thị thông tin cá nhân và liên hệ.",
        requiresOrg: false,
      },
      {
        value: "household",
        icon: "🏪",
        title: "Hộ kinh doanh",
        subtitle: "Hiển thị thông tin hộ kinh doanh và đại diện pháp luật.",
        requiresOrg: true,
      },
    ],
    methodOptions: [
      {
        value: "new",
        icon: "🆕",
        title: "Cấp mới",
        subtitle: "Khởi tạo dịch vụ Remote Signing lần đầu.",
      },
      {
        value: "renew",
        icon: "🔄",
        title: "Gia hạn",
        subtitle: "Gia hạn chứng thư số hoặc gói đã sử dụng.",
      },
    ],
    serviceTypes: [
      {
        value: "remote-signing",
        title: "Remote Signing",
        subtitle: "Dịch vụ đang được chọn cho demo.",
        selected: true,
        disabled: false,
      },
      {
        value: "token",
        title: "Token",
        subtitle: "Tùy chọn khác, hiện chưa bật trong bản demo.",
        selected: false,
        disabled: true,
      },
      {
        value: "hsm",
        title: "HSM",
        subtitle: "Tùy chọn khác, hiện chưa bật trong bản demo.",
        selected: false,
        disabled: true,
      },
    ],
    rejectionReasons: [
      "Ảnh CCCD bị mờ, không đọc được",
      "Chữ ký không khớp với CCCD",
      "GPKD hết hạn",
      "Thiếu dấu đỏ của doanh nghiệp",
    ],
    uploadRequirements: [
      {
        key: "registrationForm",
        title: "Đăng ký sử dụng",
        description: "Bản scan hoặc ảnh chụp có chữ ký.",
        extensions: ["jpg", "jpeg", "png", "pdf"],
        accept: ".jpg,.jpeg,.png,.pdf",
      },
      {
        key: "serviceContract",
        title: "Hợp đồng dịch vụ",
        description: "Bản scan hoặc ảnh chụp có chữ ký.",
        extensions: ["jpg", "jpeg", "png", "pdf"],
        accept: ".jpg,.jpeg,.png,.pdf",
      },
      {
        key: "businessLicense",
        title: "Giấy phép kinh doanh",
        description: "Bản gốc hoặc scan rõ nét.",
        extensions: ["jpg", "jpeg", "png", "pdf"],
        accept: ".jpg,.jpeg,.png,.pdf",
      },
      {
        key: "representativeId",
        title: "CCCD 2 mặt của người đại diện pháp luật",
        description: "Chỉ chấp nhận ảnh JPG hoặc PNG.",
        extensions: ["jpg", "jpeg", "png"],
        accept: ".jpg,.jpeg,.png",
      },
    ],
  },
  products: [
    {
      slug: "chu-ky-so-token",
      name: "Chữ ký số USB Token",
      shortName: "Chữ ký số",
      icon: "🔑",
      group: "PKI",
      tagline: "Chứng thư số công cộng CA2 – Ký văn bản điện tử pháp lý",
      description: "Chữ ký số CA2 Nacencomm giúp cá nhân, doanh nghiệp ký hồ sơ điện tử, kê khai thuế, hải quan, BHXH và các giao dịch điện tử có giá trị pháp lý.",
      features: ["Kê khai thuế điện tử", "Hải quan điện tử", "BHXH điện tử", "Ký hợp đồng online"],
      packages: ["1 Năm", "2 Năm", "3 Năm"],
      flowType: "standard_upload",
      requireUpload: true,
      uploadDocs: ["GPKD", "CCCD 2 mặt NDDPL", "Giấy đăng ký"],
      faqs: [
        { q: "Có dùng cho khai thuế và BHXH không?", a: "Có. Đây là nhóm use case phổ biến nhất của CA2 Token." },
        { q: "Có cần đến trực tiếp không?", a: "Trong demo website, hồ sơ được gửi online và KD liên hệ để chốt." },
      ],
    },
    {
      slug: "remote-signing",
      name: "Remote Signing",
      shortName: "Ký số từ xa",
      icon: "📱",
      group: "PKI",
      tagline: "Ký số từ xa qua điện thoại – Không cần USB Token",
      description: "Giải pháp chữ ký số từ xa CA2 Remote Signing: ký tài liệu mọi lúc mọi nơi chỉ bằng smartphone, đảm bảo an toàn và hợp pháp theo Nghị định 130/2018/NĐ-CP.",
      features: ["Không cần USB Token", "Ký mọi nơi qua app", "Xác thực sinh trắc học", "Tích hợp VNeID"],
      packages: ["1 Năm", "2 Năm", "3 Năm", "Lượt ký"],
      flowType: "remote_signing",
      requireUpload: true,
      uploadDocs: ["ĐKSD (scan)", "Hợp đồng (scan)", "GPKD gốc", "CCCD 2 mặt"],
      faqs: [
        { q: "Remote Signing khác Token ở điểm nào?", a: "Ký số hoàn toàn từ xa qua app, không cần thiết bị USB Token." },
        { q: "Có bước kích hoạt app không?", a: "Có. Demo giữ nguyên quy trình 8 bước đã đặc tả riêng." },
      ],
    },
    {
      slug: "ca2-sign-platform",
      name: "CA2 Sign Platform",
      shortName: "Sign Platform",
      icon: "🏗️",
      group: "PKI",
      tagline: "Nền tảng ký số tập trung cho doanh nghiệp & tổ chức lớn",
      description: "CA2 Platform cung cấp giải pháp ký số quy mô lớn, tích hợp API, quản lý tập trung, phù hợp ngân hàng, bảo hiểm, cơ quan nhà nước.",
      features: ["API tích hợp hệ thống", "Quản lý tập trung", "Batch signing", "Audit log"],
      packages: ["Enterprise – Liên hệ"],
      flowType: "consult",
      requireUpload: false,
      faqs: [
        { q: "Có hỗ trợ tích hợp API không?", a: "Có. Đây là một trong những điểm mạnh của CA2 Sign Platform." },
        { q: "Phù hợp doanh nghiệp nào?", a: "Ngân hàng, bảo hiểm, tập đoàn và cơ quan nhà nước." },
      ],
    },
    {
      slug: "hoa-don-dien-tu",
      name: "Hóa đơn điện tử CA2-EInvoice",
      shortName: "Hóa đơn điện tử",
      icon: "🧾",
      group: "Kế toán - Thuế",
      tagline: "Phát hành hóa đơn điện tử đúng chuẩn Nghị định 123/2020/NĐ-CP",
      description: "CA2-EInvoice hỗ trợ doanh nghiệp phát hành, quản lý hóa đơn điện tử có mã xác thực của cơ quan thuế, tích hợp trực tiếp với hệ thống kế toán.",
      features: ["Kết nối cơ quan thuế", "Phát hành tức thì", "Lưu trữ điện tử", "Tích hợp phần mềm kế toán"],
      packages: ["Gói 300 HD/năm", "Gói 1.000 HD/năm", "Gói Không giới hạn"],
      flowType: "standard_form",
      requireUpload: true,
      uploadDocs: ["GPKD", "Quyết định sử dụng HĐĐT"],
      extraFields: ["accountingSoftware", "invoiceVolume"],
      faqs: [
        { q: "Có tích hợp phần mềm kế toán không?", a: "Có thể mock như đã tích hợp trực tiếp với hệ thống kế toán hiện hữu." },
        { q: "Doanh nghiệp mới có dùng được không?", a: "Có, chỉ cần khai báo đúng MST và hồ sơ pháp lý." },
      ],
    },
    {
      slug: "phan-mem-ke-toan",
      name: "Phần mềm kế toán",
      shortName: "Kế toán",
      icon: "📊",
      group: "Kế toán - Thuế",
      tagline: "Quản lý tài chính kế toán toàn diện cho doanh nghiệp vừa và nhỏ",
      description: "Phần mềm kế toán CA2 giúp doanh nghiệp quản lý sổ sách, lập báo cáo tài chính, kê khai thuế nhanh chóng và chính xác.",
      features: ["Kê khai thuế tự động", "Báo cáo tài chính chuẩn", "Quản lý công nợ", "Kết nối ngân hàng"],
      packages: ["Gói Cơ bản", "Gói Tiêu chuẩn", "Gói Nâng cao"],
      flowType: "standard_form",
      requireUpload: false,
      extraFields: ["userCount", "currentSoftware"],
      faqs: [
        { q: "Có phù hợp SME không?", a: "Có, gói demo tập trung cho doanh nghiệp vừa và nhỏ." },
        { q: "Có cần chuyển dữ liệu cũ không?", a: "Trong triển khai thực tế có thể hỗ trợ chuyển đổi dữ liệu." },
      ],
    },
    {
      slug: "phan-mem-bao-hiem",
      name: "Phần mềm bảo hiểm",
      shortName: "Bảo hiểm",
      icon: "🛡️",
      group: "Bảo hiểm",
      tagline: "Quản lý hợp đồng bảo hiểm & kê khai BHXH trực tuyến",
      description: "Giải pháp phần mềm quản lý bảo hiểm xã hội, bảo hiểm y tế, khai báo điện tử và kết nối cơ quan BHXH.",
      features: ["Kê khai BHXH điện tử", "Quản lý hợp đồng", "Nhắc nhở đóng bảo hiểm", "Báo cáo tự động"],
      packages: ["Theo số nhân viên", "Gói doanh nghiệp"],
      flowType: "standard_form",
      requireUpload: false,
      extraFields: ["employeeCount"],
      faqs: [
        { q: "Có theo số nhân viên không?", a: "Có. Gói demo cho phép chọn theo quy mô nhân sự." },
        { q: "Có tích hợp BHXH điện tử không?", a: "Có trong mô tả sản phẩm và quy trình tư vấn." },
      ],
    },
    {
      slug: "cham-cong-tinh-luong",
      name: "Chấm công – Tính lương",
      shortName: "HR",
      icon: "⏰",
      group: "Nhân sự",
      tagline: "Tự động hóa chấm công, tính lương và quản lý nhân sự",
      description: "Hệ thống chấm công điện tử tích hợp tính lương tự động, quản lý phép nghỉ, hợp đồng lao động và báo cáo nhân sự.",
      features: ["Chấm công khuôn mặt / vân tay", "Tính lương tự động", "Quản lý ca làm việc", "Báo cáo thuế TNCN"],
      packages: ["≤ 20 NV", "≤ 100 NV", "Không giới hạn"],
      flowType: "standard_form",
      requireUpload: false,
      extraFields: ["employeeCount", "attendanceDevice"],
      faqs: [
        { q: "Có hỗ trợ máy chấm công không?", a: "Có thể ghi nhận thiết bị hiện tại để KD tư vấn phương án phù hợp." },
        { q: "Có tính lương theo ca không?", a: "Có trong phần tính năng mock của sản phẩm." },
      ],
    },
    {
      slug: "security-pentest",
      name: "Rà soát lỗ hổng – Security",
      shortName: "Security",
      icon: "🔍",
      group: "An ninh mạng",
      tagline: "Kiểm thử bảo mật & đánh giá rủi ro hệ thống CNTT",
      description: "Dịch vụ pentest, rà soát lỗ hổng bảo mật, đánh giá an toàn thông tin theo tiêu chuẩn ISO 27001 và quy định của Bộ TT&TT.",
      features: ["Pentest Web App", "Pentest hạ tầng mạng", "Đánh giá ATTT", "Báo cáo & khuyến nghị"],
      packages: ["Gói Cơ bản", "Gói Toàn diện", "Gói Doanh nghiệp"],
      flowType: "consult_schedule",
      requireUpload: false,
      extraFields: ["systemDescription", "systemScale", "surveyDate"],
      faqs: [
        { q: "Có khảo sát trước khi báo giá không?", a: "Có. Đây là flow consult_schedule trong bản demo." },
        { q: "Có báo cáo sau pentest không?", a: "Có, kèm khuyến nghị xử lý rủi ro." },
      ],
    },
    {
      slug: "tu-van-ha-tang-anninh",
      name: "Tư vấn & Xây dựng hạ tầng An ninh",
      shortName: "Hạ tầng ATTT",
      icon: "🏛️",
      group: "An ninh mạng",
      tagline: "Thiết kế và triển khai hạ tầng an toàn thông tin cho tổ chức",
      description: "Nacencomm tư vấn, thiết kế và triển khai hạ tầng PKI, HSM, hệ thống xác thực điện tử và an ninh mạng cho cơ quan nhà nước và doanh nghiệp lớn.",
      features: ["Thiết kế PKI nội bộ", "Triển khai HSM", "Xác thực 2 lớp", "Đào tạo an toàn thông tin"],
      packages: ["Liên hệ tư vấn"],
      flowType: "consult",
      requireUpload: false,
      faqs: [
        { q: "Có triển khai HSM không?", a: "Có. Đây là một nhóm dịch vụ chính trong trang demo này." },
        { q: "Có phù hợp cơ quan nhà nước không?", a: "Có, cả cơ quan nhà nước và doanh nghiệp lớn." },
      ],
    },
    {
      slug: "dau-thau-online",
      name: "Cung cấp tài khoản đấu thầu",
      shortName: "Đấu thầu",
      icon: "📋",
      group: "Chính phủ điện tử",
      tagline: "Đăng ký tài khoản hệ thống đấu thầu quốc gia muasamcong.mpi.gov.vn",
      description: "Hỗ trợ doanh nghiệp đăng ký, cấp và gia hạn tài khoản tham gia đấu thầu điện tử trên hệ thống mua sắm công quốc gia.",
      features: ["Đăng ký tài khoản nhanh", "Hỗ trợ hồ sơ pháp lý", "Tư vấn thủ tục", "Gia hạn tài khoản"],
      packages: ["Cấp mới", "Gia hạn"],
      flowType: "standard_upload",
      requireUpload: true,
      uploadDocs: ["GPKD/Quyết định thành lập", "CCCD NDDPL", "Giấy ủy quyền (nếu có)"],
      faqs: [
        { q: "Có hỗ trợ cấp mới và gia hạn không?", a: "Có, cả 2 nhóm nhu cầu đều được mô phỏng." },
        { q: "Có yêu cầu hồ sơ pháp lý không?", a: "Có, upload ở bước hồ sơ điện tử." },
      ],
    },
    {
      slug: "chuyen-doi-so",
      name: "Dịch vụ chuyển đổi số",
      shortName: "CĐS",
      icon: "🚀",
      group: "Chuyển đổi số",
      tagline: "Đồng hành toàn diện trên hành trình chuyển đổi số doanh nghiệp",
      description: "Nacencomm cung cấp giải pháp chuyển đổi số tổng thể: từ tư vấn chiến lược, triển khai hệ thống đến đào tạo nhân sự.",
      features: ["Tư vấn chiến lược CĐS", "Triển khai hệ thống", "Đào tạo nhân sự", "Hỗ trợ vận hành"],
      packages: ["Khảo sát miễn phí", "Gói triển khai"],
      flowType: "consult_survey",
      requireUpload: false,
      extraFields: ["industry", "businessScale", "currentProblem"],
      faqs: [
        { q: "Có khảo sát nhu cầu trước không?", a: "Có. Flow consult_survey được dựng riêng cho nhóm này." },
        { q: "Có đào tạo nội bộ không?", a: "Có trong phần dịch vụ và chuyển giao." },
      ],
    },
    {
      slug: "stem-hoc-tap",
      name: "STEM Học tập",
      shortName: "STEM",
      icon: "🎓",
      group: "Giáo dục",
      tagline: "Nền tảng học STEM & công nghệ số cho học sinh, sinh viên",
      description: "Chương trình đào tạo STEM, lập trình, an toàn thông tin và kỹ năng số dành cho trường học, trung tâm và cá nhân.",
      features: ["Lập trình cơ bản – nâng cao", "Kỹ năng số", "An toàn thông tin", "Chứng chỉ kỹ năng số"],
      packages: ["Gói Cá nhân", "Gói Trường học", "Gói Trung tâm"],
      flowType: "course_register",
      requireUpload: false,
      extraFields: ["schoolOrg", "studentCount", "interestedCourse"],
      faqs: [
        { q: "Có gói cho trường học không?", a: "Có, cùng với gói cá nhân và trung tâm." },
        { q: "Có thể đăng ký theo lớp không?", a: "Có thể điền số lượng học viên trong form." },
      ],
    },
    {
      slug: "ca2-co-van",
      name: "CA2 CO-VAN – Khai báo CO",
      shortName: "CO-VAN",
      icon: "📦",
      group: "Xuất nhập khẩu",
      tagline: "Số hóa quy trình kê khai Giấy chứng nhận xuất xứ (CO) điện tử",
      description: "CA2 CO-VAN giúp doanh nghiệp XNK số hóa hoàn toàn quy trình khai báo CO, kết nối hệ thống tiếp nhận tập trung VCCI, giảm chi phí và thời gian.",
      features: ["Khai báo CO điện tử", "Kết nối VCCI tự động", "Lưu trữ pháp lý lâu dài", "Cập nhật chuẩn thông điệp"],
      packages: ["Gói Doanh nghiệp nhỏ", "Gói Tiêu chuẩn", "Gói Lớn"],
      flowType: "standard_upload",
      requireUpload: true,
      uploadDocs: ["GPKD", "Hợp đồng thương mại", "Tờ khai hải quan mẫu"],
      faqs: [
        { q: "Có kết nối VCCI không?", a: "Có trong nội dung mô tả và lợi ích sản phẩm." },
        { q: "Có cần upload hồ sơ mẫu không?", a: "Có, flow upload được bật cho sản phẩm này." },
      ],
    },
    {
      slug: "ekyc",
      name: "eKYC – Xác thực điện tử",
      shortName: "eKYC",
      icon: "🪪",
      group: "PKI",
      tagline: "Xác thực danh tính điện tử tích hợp VNeID & sinh trắc học",
      description: "Giải pháp eKYC tích hợp nhận diện khuôn mặt, đọc chip CCCD, xác thực qua VNeID – phù hợp ngân hàng, bảo hiểm, fintech và cơ quan nhà nước.",
      features: ["Nhận diện khuôn mặt", "Đọc chip CCCD/hộ chiếu", "Tích hợp VNeID", "API linh hoạt"],
      packages: ["Demo API miễn phí", "Gói sản xuất"],
      flowType: "consult",
      requireUpload: false,
      faqs: [
        { q: "Có demo API không?", a: "Có. Đây là CTA chính trên sản phẩm eKYC." },
        { q: "Có hỗ trợ VNeID không?", a: "Có trong mô tả và tính năng sản phẩm." },
      ],
    },
  ],
};
